name: Terraform Automation

on:
  push:
    branches:
    - stage

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: stage # Checkout the staging branch

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1


    - name: Configure AWS Credentials (using environment variables)
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1 # adjust region as needed
      run: |
        terraform init -chdir=terraform
        terraform plan -chdir=terraform
